### PR TITLE
SEC-2808: Add CODEOWNERS and .buginfo files

### PR DESCRIPTION
**Pull request by obrie**
https://jira.unity3d.com/browse/OSEC-2808

In order to help us integrate better with various Unity tools, we are creating `CODEOWNERS` and `.buginfo` files in all of our repositories.  You can learn more about these in the Jira ticket.

The assignments in this PR are based on assessments from this spreadsheet:

* https://docs.google.com/spreadsheets/d/1ufKQiMK4NZM-6LNfLhO-93MBDdAJXh1S6oQppiRcHkw/edit#gid=705595020

Relevant links:

* [Github team](https://github.com/orgs/Tapjoy/teams/eng-group-ops)
* [Jira project](https://jira.unity3d.com/browse/OPER)

What we're primarily looking for out of this PR review:

* Ensure that the proper team and Jira project are being assigned
* Ensure there are no syntax issues called out by github in the `CODEOWNERS` file

### CODE REVIEW

**Comment by StabbyCutyou** [comment]
When is the next release of state_machine?

I'm awaiting several bug fixes.

**Review by adamy318 — APPROVED** [review]
LGTM

**Comment by geoffreyclark** [comment]
Will you guys just approve this already? It's one off my list of about 160 repos to approve, thanks!

**Comment by jjrussell** [comment]
Can this be rolled into a plug-in of the week? I haven't seen one in a little while. Are those still a thing?

**Comment by TheRealBenJones** [comment]
Are we sure we have decided on Jira? Seems like that architectural decision was not fully discussed in the PR so far

**Pull request merged**
